apiVersion: v1
kind: Service
metadata:
  name: mysvc
  namespace: webapps
spec:
  selector:
    app: blue
    version: blue # This will be updated dynamically by the pipeline
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: NodePort
